# Generated by Django 4.2.18 on 2025-02-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('section', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
